services:
  - type: web
    name: userskins-portfolio
    env: node
    plan: free
    region: oregon
    nodeVersion: 20
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production

